export const styles = {
  filterBar: 'flex flex-wrap items-end gap-3 border-b border-line px-4 py-3',
  search: 'w-64',
  name: 'text-[13px] font-semibold text-text',
  slug: 'font-mono text-[11px] text-text-subtle',
  muted: 'text-[12px] text-text-subtle',
  num: 'tabular-nums text-[13px] text-text',
  pager: 'flex flex-wrap items-center justify-between gap-3 border-t border-line px-4 py-3',
  pagerInfo: 'text-xs text-text-subtle',
  pagerActions: 'flex items-center gap-2',
  layout: 'grid gap-5 xl:grid-cols-5',
  main: 'xl:col-span-3',
  side: 'xl:col-span-2 flex flex-col gap-5',
  formGrid: 'grid gap-4 md:grid-cols-2',
  formFull: 'md:col-span-2',
  actions: 'flex flex-wrap items-center justify-end gap-2 border-t border-line px-5 py-4',
  stopRow: 'flex flex-col gap-2 border-b border-line px-5 py-3 last:border-b-0',
  stopHead: 'flex items-center gap-3',
  stopPos: 'w-6 shrink-0 text-center font-mono text-[11px] text-text-subtle',
  stopTitle: 'text-[13px] font-semibold text-text',
  stopMeta: 'text-[11px] text-text-subtle',
  stopActions: 'ml-auto flex shrink-0 items-center gap-1',
  stopGrid: 'grid gap-2 pl-9 md:grid-cols-2',
  statusRow: 'flex flex-wrap items-center gap-2 px-5 py-4',
  note: 'mx-5 mb-4 flex items-start gap-2 rounded-compact border border-amber/40 bg-amber-soft px-3 py-2 text-xs text-text',
  separation:
    'rounded-compact bg-surface-muted px-3 py-2 text-[11px] leading-relaxed text-text-subtle',
} as const
