import type {
  Collection,
  CmsPlaceDetail,
  FeatureFlag,
  ModerationQueue,
  OpsKpis,
  RankingConfig,
  Taxonomy,
} from '@/shared/api/contracts'
import type { ImportJob, ImportRow } from '@/shared/api/contracts-import'

/**
 * Dev/test fixtures. Vietnamese content on purpose — vi is the product
 * default and the layout has to survive real diacritics and real name length.
 * No real personal data: authors are pseudonymous handles.
 */

const now = Date.UTC(2026, 7, 27, 9, 0, 0)
const iso = (offsetMinutes: number) => new Date(now - offsetMinutes * 60_000).toISOString()

export const taxonomies: Taxonomy[] = [
  {
    id: 'tx-mood-quiet',
    kind: 'mood',
    key: 'quiet_peaceful',
    labels: { vi: 'Yên tĩnh', en: 'Quiet & peaceful' },
    sortOrder: 1,
    isActive: true,
    usageCount: 2814,
    synonyms: [
      { term: 'yên lặng', locale: 'vi' },
      { term: 'không ồn ào', locale: 'vi' },
      { term: 'peaceful', locale: 'en' },
    ],
  },
  {
    id: 'tx-mood-energetic',
    kind: 'mood',
    key: 'high_energy',
    labels: { vi: 'Sống động', en: 'Energetic' },
    sortOrder: 2,
    isActive: true,
    usageCount: 1402,
    synonyms: [{ term: 'nhộn nhịp', locale: 'vi' }],
  },
  {
    id: 'tx-mood-chill',
    kind: 'mood',
    key: 'chill_lounge',
    labels: { vi: 'Thư giãn', en: 'Relaxed lounge' },
    sortOrder: 3,
    isActive: false,
    usageCount: 0,
    synonyms: [],
  },
  {
    id: 'tx-cat-cafe',
    kind: 'category',
    key: 'cafe',
    labels: { vi: 'Cà phê', en: 'Cafe' },
    sortOrder: 1,
    isActive: true,
    usageCount: 6120,
    synonyms: [{ term: 'quán cà phê', locale: 'vi' }],
  },
  {
    id: 'tx-cat-street-food',
    kind: 'category',
    key: 'street_food',
    labels: { vi: 'Ăn vặt vỉa hè', en: 'Street food' },
    sortOrder: 2,
    isActive: true,
    usageCount: 3980,
    synonyms: [],
  },
  {
    id: 'tx-set-workfriendly',
    kind: 'setting',
    key: 'work_friendly',
    labels: { vi: 'Ngồi làm việc được', en: 'Work friendly' },
    sortOrder: 1,
    isActive: true,
    usageCount: 1180,
    synonyms: [{ term: 'có ổ cắm', locale: 'vi' }],
  },
  {
    id: 'tx-diet-vegan',
    kind: 'dietary',
    key: 'vegan',
    labels: { vi: 'Thuần chay', en: 'Vegan' },
    sortOrder: 1,
    isActive: true,
    usageCount: 214,
    synonyms: [],
  },
  {
    id: 'tx-acc-wheelchair',
    kind: 'accessibility',
    key: 'wheelchair_access',
    labels: { vi: 'Xe lăn tiếp cận được', en: 'Wheelchair access' },
    sortOrder: 1,
    isActive: true,
    usageCount: 96,
    synonyms: [],
  },
  {
    id: 'tx-spend-mid',
    kind: 'spending_style',
    key: 'mid_range',
    labels: { vi: 'Tầm trung', en: 'Mid range' },
    sortOrder: 2,
    isActive: true,
    usageCount: 4410,
    synonyms: [],
  },
  {
    id: 'tx-suit-couple',
    kind: 'suitability',
    key: 'couple_date',
    labels: { vi: 'Hẹn hò đôi', en: 'Couple date' },
    sortOrder: 1,
    isActive: true,
    usageCount: 5320,
    synonyms: [],
  },
]

/**
 * Catalog rows in the shape `GET /cms/places` actually returns
 * (`CmsPlaceListItem`): lean, no address, no taxonomy, one blended rating.
 */
export const places: CmsPlaceDetail[] = [
  {
    id: 'pl-chao-ban',
    name: 'Chào Bạn Cafe & Space',
    status: 'published',
    areaKey: 'hcm_q3',
    rating: 4.8,
    confidence: 0.92,
    freshnessCheckedAt: iso(60 * 48),
    createdAt: iso(60 * 24 * 200),
    updatedAt: iso(120),
    // Everything below only exists on the mocked detail endpoint.
    description: 'Cà phê nhiều cây, ba tầng, phù hợp ngồi làm việc cả buổi.',
    addressText: '126 Nguyễn Thị Minh Khai, Quận 3, TP.HCM',
    lat: 10.7769,
    lng: 106.6953,
    avgVisitMinutes: 90,
    isLodging: false,
    curatedRank: 3,
    taxonomyKeys: ['cafe', 'work_friendly', 'quiet_peaceful'],
    taxonomyIds: ['tx-cat-cafe', 'tx-set-workfriendly', 'tx-mood-quiet'],
    ratings: {
      googleRating: 4.8,
      googleRatingCount: 1240,
      gogoRating: 4.9,
      gogoRatingCount: 86,
      compositeScore: 0.91,
    },
    sourceCount: 4,
    updatedBy: 'huy.ng',
    // 0 = Sunday … 6 = Saturday, matching GoGo-BE's `vnDayMinute()`.
    hours: [
      { dayOfWeek: 0, openMinute: 480, closeMinute: 1350, isOvernight: false },
      { dayOfWeek: 1, openMinute: 420, closeMinute: 1350, isOvernight: false },
      { dayOfWeek: 2, openMinute: 420, closeMinute: 1350, isOvernight: false },
      { dayOfWeek: 3, openMinute: 420, closeMinute: 1350, isOvernight: false },
      { dayOfWeek: 4, openMinute: 420, closeMinute: 1350, isOvernight: false },
      { dayOfWeek: 5, openMinute: 420, closeMinute: 1380, isOvernight: false },
      { dayOfWeek: 6, openMinute: 480, closeMinute: 1380, isOvernight: false },
    ],
    prices: [
      {
        id: 'pr-1',
        priceMin: 45_000,
        priceMax: 90_000,
        currency: 'VND',
        unit: 'per_person',
        observedAt: iso(60 * 24 * 3),
        observedBy: 'vy.vo',
      },
    ],
    sources: [
      {
        kind: 'google_places',
        label: 'Google Places',
        fetchedAt: iso(60 * 48),
        attribution: 'Dữ liệu © Google',
      },
      {
        kind: 'editor',
        label: 'Biên tập viên xác minh',
        fetchedAt: iso(60 * 24 * 3),
        attribution: null,
      },
    ],
    media: [],
  },
  {
    id: 'pl-pho-bat-dan',
    name: 'Phở Bát Đàn',
    status: 'published',
    areaKey: 'hn_hoankiem',
    rating: 4.5,
    confidence: 0.78,
    freshnessCheckedAt: iso(60 * 24 * 14),
    createdAt: iso(60 * 24 * 180),
    updatedAt: iso(60 * 26),
    description: 'Phở bò truyền thống, xếp hàng tự bưng.',
    addressText: '49 Bát Đàn, Hoàn Kiếm, Hà Nội',
    lat: 21.0333,
    lng: 105.8452,
    avgVisitMinutes: 40,
    isLodging: false,
    curatedRank: null,
    taxonomyKeys: ['street_food'],
    taxonomyIds: ['tx-cat-street-food'],
    ratings: {
      googleRating: 4.5,
      googleRatingCount: 8210,
      gogoRating: 4.7,
      gogoRatingCount: 41,
      compositeScore: 0.88,
    },
    sourceCount: 2,
    updatedBy: 'vy.vo',
    hours: [],
    prices: [],
    sources: [
      {
        kind: 'google_places',
        label: 'Google Places',
        fetchedAt: iso(60 * 24 * 14),
        attribution: 'Dữ liệu © Google',
      },
    ],
    media: [],
  },
  {
    id: 'pl-tay-ho-sup',
    name: 'Tây Hồ Sunset SUP Club',
    status: 'review',
    areaKey: 'hn_tayho',
    rating: 4.2,
    confidence: 0.44,
    freshnessCheckedAt: null,
    createdAt: iso(60 * 24 * 20),
    updatedAt: iso(60 * 72),
    description: null,
    addressText: '11 Tứ Hoa, Tây Hồ, Hà Nội',
    lat: 21.0705,
    lng: 105.8221,
    avgVisitMinutes: 120,
    isLodging: false,
    curatedRank: null,
    taxonomyKeys: ['high_energy'],
    taxonomyIds: ['tx-mood-energetic'],
    ratings: {
      googleRating: 4.2,
      googleRatingCount: 310,
      gogoRating: null,
      gogoRatingCount: 0,
      compositeScore: null,
    },
    sourceCount: 1,
    updatedBy: 'dung.tr',
    hours: [],
    prices: [],
    sources: [],
    media: [],
  },
  {
    id: 'pl-goplay',
    name: 'GoPlay Entertainment',
    status: 'suspended',
    areaKey: 'hcm_q10',
    rating: 4.1,
    confidence: 0.35,
    freshnessCheckedAt: iso(60 * 24 * 120),
    createdAt: iso(60 * 24 * 300),
    updatedAt: iso(60 * 24 * 12),
    description: null,
    addressText: '812 Sư Vạn Hạnh, Quận 10, TP.HCM',
    lat: 10.7712,
    lng: 106.6702,
    avgVisitMinutes: 150,
    isLodging: false,
    curatedRank: null,
    taxonomyKeys: ['high_energy'],
    taxonomyIds: ['tx-mood-energetic'],
    ratings: {
      googleRating: 4.1,
      googleRatingCount: 520,
      gogoRating: 3.5,
      gogoRatingCount: 12,
      compositeScore: 0.61,
    },
    sourceCount: 3,
    updatedBy: 'system',
    hours: [],
    prices: [],
    sources: [],
    media: [],
  },
  {
    id: 'pl-com-tam-ba-ghien',
    name: 'Cơm Tấm Ba Ghiền',
    status: 'community_submitted',
    areaKey: 'hcm_phunhuan',
    rating: 4.4,
    confidence: 0.5,
    freshnessCheckedAt: null,
    createdAt: iso(60 * 5),
    updatedAt: iso(60 * 5),
    description: null,
    addressText: '84 Đặng Văn Ngữ, Phú Nhuận, TP.HCM',
    lat: 10.7955,
    lng: 106.6752,
    avgVisitMinutes: 45,
    isLodging: false,
    curatedRank: null,
    taxonomyKeys: ['street_food'],
    taxonomyIds: ['tx-cat-street-food'],
    ratings: {
      googleRating: 4.4,
      googleRatingCount: 4100,
      gogoRating: null,
      gogoRatingCount: 0,
      compositeScore: null,
    },
    sourceCount: 1,
    updatedBy: 'import',
    hours: [],
    prices: [],
    sources: [],
    media: [],
  },
]

/** Raw rows, exactly as `GET /cms/places/duplicates` returns them. */
export const duplicateRows = [
  {
    place_a: 'pl-chao-ban',
    place_b: 'pl-chao-ban-bistro',
    name_a: 'Chào Bạn Cafe & Space',
    name_b: 'Chào Bạn Bistro & Cafe',
    name_similarity: 0.94,
    distance_m: 38,
  },
]

/** Bare array of headers — the list endpoint returns no items and no cover. */
export const collections: Collection[] = [
  {
    id: 'col-cafe-q3',
    slug: 'top-cafe-song-ao-q3',
    locale: 'vi',
    title: 'Top cà phê sống ảo Quận 3',
    status: 'published',
    startsAt: iso(60 * 24 * 10),
    endsAt: null,
  },
  {
    id: 'col-hanoi-night',
    slug: 'an-dem-ha-noi',
    locale: 'vi',
    title: 'Ăn đêm Hà Nội',
    status: 'scheduled',
    startsAt: iso(-60 * 24),
    endsAt: iso(-60 * 24 * 30),
  },
]

/** Four independent pending lists, PII-light, exactly as the service builds them. */
export const moderationQueue: ModerationQueue = {
  reviews: [
    {
      id: 'mr-1',
      rating: 5,
      text: 'Check-in view đẹp, hoàng hôn hồ Tây rất đáng đi.',
      createdAt: iso(34),
    },
    { id: 'mr-2', rating: 2, text: 'Nhân viên thái độ, chờ quá lâu.', createdAt: iso(150) },
  ],
  reports: [
    { id: 'rp-1', targetType: 'review', targetId: 'mr-2', reasonCode: 'ABUSIVE_LANGUAGE' },
    {
      id: 'rp-2',
      targetType: 'place',
      targetId: 'pl-pho-bat-dan',
      reasonCode: 'PERMANENTLY_CLOSED',
    },
  ],
  checkins: [
    {
      id: 'ci-1',
      rating: 4,
      note: 'Ảnh hoá đơn và không gian tầng 2.',
      photoCount: 3,
      hasBill: true,
    },
  ],
  communityPlaces: [
    { id: 'pl-com-tam-ba-ghien', name: 'Cơm Tấm Ba Ghiền', createdAt: iso(60 * 5) },
  ],
}

/** The six aggregates `CmsOpsService#kpis` returns — nothing more. */
export const opsKpis: OpsKpis = {
  placeFreshness: { fresh: 18_420, stale: 2_120, unknown: 700 },
  zeroResultsLast7d: 412,
  suggestionRunsLast7d: { succeeded: 1_884, failed: 240 },
  currentPlansOverBudget: 37,
  providerErrorsLast7d: 12,
  moderationBacklog: { reviews: 2, reports: 2 },
}

export const rankingConfigs: RankingConfig[] = [
  {
    id: 'rc-2',
    key: 'suggestion.scoring',
    version: 2,
    status: 'active',
    weights: {
      preferenceMatch: 0.85,
      groupFairness: 0.6,
      distanceDecay: 0.75,
      budgetFit: 0.3,
      freshness: 0.4,
    },
    createdBy: 'minh.anh',
    createdAt: iso(120),
    approvedBy: 'vy.vo',
    approvedAt: iso(110),
    activatedAt: iso(105),
  },
  {
    id: 'rc-1',
    key: 'suggestion.scoring',
    version: 1,
    status: 'superseded',
    weights: {
      preferenceMatch: 0.8,
      groupFairness: 0.55,
      distanceDecay: 0.7,
      budgetFit: 0.35,
      freshness: 0.35,
    },
    createdBy: 'vy.vo',
    createdAt: iso(60 * 24 * 14),
    approvedBy: 'minh.anh',
    approvedAt: iso(60 * 24 * 14),
    activatedAt: iso(60 * 24 * 14),
  },
]

export const rankingBounds = [
  { weight: 'preferenceMatch', min: 0, max: 1, step: 0.01 },
  { weight: 'groupFairness', min: 0, max: 1, step: 0.01 },
  { weight: 'distanceDecay', min: 0, max: 1, step: 0.01 },
  { weight: 'budgetFit', min: 0, max: 1, step: 0.01 },
  { weight: 'freshness', min: 0, max: 1, step: 0.01 },
]

export const featureFlags: FeatureFlag[] = [
  {
    key: 'suggestion.ai_refinement',
    enabled: true,
    description:
      'Cho phép AI tinh chỉnh trên tập ứng viên đã hợp lệ. Tắt để quay về kết quả deterministic.',
    rolloutPercent: 100,
    isKillSwitch: true,
    updatedBy: 'minh.anh',
    updatedAt: iso(240),
  },
  {
    key: 'ingest.auto_publish_community',
    enabled: false,
    description: 'Tự động xuất bản địa điểm do người dùng gửi sau khi verify.',
    rolloutPercent: 0,
    isKillSwitch: false,
    updatedBy: 'vy.vo',
    updatedAt: iso(60 * 24 * 4),
  },
  {
    key: 'search.vi_synonym_expansion',
    enabled: true,
    description: 'Mở rộng truy vấn tiếng Việt bằng bảng từ đồng nghĩa.',
    rolloutPercent: 100,
    isKillSwitch: false,
    updatedBy: 'huy.ng',
    updatedAt: iso(60 * 24 * 9),
  },
]

export const importJobs: ImportJob[] = [
  {
    id: '4f0b8e10-0000-4000-8000-000000000209',
    status: 'review_required',
    mode: 'create_drafts',
    sourceType: 'xlsx',
    sourceFileName: 'hcm_q3_cafe_batch4.xlsx',
    totals: { rows: 500, processed: 234, success: 210, warnings: 18, failed: 6 },
    createdAt: iso(45),
    completedAt: null,
    createdBy: 'huy.ng',
    defaultCity: 'Hồ Chí Minh',
    rowsByStatus: { needs_confirmation: 12, duplicate: 4, ready: 210, failed: 6, pending: 266 },
    startedAt: iso(44),
    cancelledAt: null,
    reused: false,
    unmappedHeaders: ['ghi_chu_noi_bo'],
  },
  {
    id: '4f0b8e10-0000-4000-8000-000000000208',
    status: 'completed',
    mode: 'publish_approved',
    sourceType: 'csv',
    sourceFileName: 'chuoi_tra_sua_audit.csv',
    totals: { rows: 1240, processed: 1240, success: 1226, warnings: 9, failed: 14 },
    createdAt: iso(60 * 26),
    completedAt: iso(60 * 25),
    createdBy: 'vy.vo',
    defaultCity: null,
    rowsByStatus: { imported: 1226, failed: 14 },
    startedAt: iso(60 * 26),
    cancelledAt: null,
    reused: false,
    unmappedHeaders: [],
  },
  {
    id: '4f0b8e10-0000-4000-8000-000000000207',
    status: 'paused_provider_quota',
    mode: 'create_drafts',
    sourceType: 'google_sheet',
    sourceFileName: 'dalat_homestay_geocoded',
    totals: { rows: 300, processed: 22, success: 20, warnings: 2, failed: 0 },
    createdAt: iso(60 * 72),
    completedAt: null,
    createdBy: 'minh.anh',
    defaultCity: 'Đà Lạt',
    rowsByStatus: { pending: 278, ready: 20 },
    startedAt: iso(60 * 72),
    cancelledAt: null,
    reused: false,
    unmappedHeaders: [],
  },
]

export const importRows: Record<string, ImportRow[]> = {
  [importJobs[0]!.id]: [
    {
      id: 'row-12',
      rowNumber: 12,
      sourceRowId: '12',
      status: 'needs_confirmation',
      normalized: {
        name: 'Cộng Cà Phê',
        address: '120 Nguyễn Thị Minh Khai',
        city: 'Hồ Chí Minh',
        category: 'cafe',
      },
      resolvedGooglePlaceId: null,
      matchedPlaceId: null,
      matchedPlaceName: null,
      matchConfidence: 0.82,
      matchReasons: ['MULTIPLE_BRANCHES', 'EXACT_NAME_CITY'],
      candidates: [
        {
          googlePlaceId: 'ChIJ_cong_q3',
          name: 'Cộng Cà Phê – Nguyễn Thị Minh Khai',
          address: '120 Nguyễn Thị Minh Khai, Quận 3',
          confidence: 0.86,
          lat: 10.7771,
          lng: 106.6942,
          rating: 4.4,
          ratingCount: 1980,
          photoUrl: null,
          fetchedAt: iso(45),
          attributions: ['Dữ liệu © Google'],
        },
        {
          googlePlaceId: 'ChIJ_cong_q1',
          name: 'Cộng Cà Phê – Lý Tự Trọng',
          address: '26 Lý Tự Trọng, Quận 1',
          confidence: 0.71,
          lat: 10.7801,
          lng: 106.7002,
          rating: 4.3,
          ratingCount: 2410,
          photoUrl: null,
          fetchedAt: iso(45),
          attributions: ['Dữ liệu © Google'],
        },
      ],
      errors: [],
      warnings: [
        {
          code: 'DISTRICT_MISMATCH',
          field: 'district',
          message: 'Quận trong nguồn khác quận nhà cung cấp',
        },
      ],
    },
    {
      id: 'row-13',
      rowNumber: 13,
      sourceRowId: '13',
      status: 'ready',
      normalized: {
        name: 'The Coffee House Cao Thắng',
        address: '86 Cao Thắng',
        city: 'Hồ Chí Minh',
      },
      resolvedGooglePlaceId: 'ChIJ_tch_caothang',
      matchedPlaceId: null,
      matchedPlaceName: null,
      matchConfidence: 0.99,
      matchReasons: ['EXACT_PROVIDER_ID'],
      candidates: [],
      errors: [],
      warnings: [],
    },
    {
      id: 'row-14',
      rowNumber: 14,
      sourceRowId: '14',
      status: 'duplicate',
      normalized: {
        name: 'Chào Bạn Cafe',
        address: '126 Nguyễn Thị Minh Khai',
        city: 'Hồ Chí Minh',
      },
      resolvedGooglePlaceId: 'ChIJ_chao_ban',
      matchedPlaceId: 'pl-chao-ban',
      matchedPlaceName: 'Chào Bạn Cafe & Space',
      matchConfidence: 0.97,
      matchReasons: ['EXACT_PROVIDER_ID'],
      candidates: [],
      errors: [],
      warnings: [],
    },
    {
      id: 'row-15',
      rowNumber: 15,
      sourceRowId: '15',
      status: 'validation_failed',
      normalized: { name: 'Quán không tên', address: '' },
      resolvedGooglePlaceId: null,
      matchedPlaceId: null,
      matchedPlaceName: null,
      matchConfidence: null,
      matchReasons: [],
      candidates: [],
      errors: [{ code: 'ADDRESS_REQUIRED', field: 'address', message: 'Thiếu địa chỉ' }],
      warnings: [],
    },
    {
      id: 'row-16',
      rowNumber: 16,
      sourceRowId: '16',
      status: 'unresolved',
      normalized: { name: 'Cafe Tầng Thượng 3B', address: 'Ngõ 12 Trần Quốc Toản' },
      resolvedGooglePlaceId: null,
      matchedPlaceId: null,
      matchedPlaceName: null,
      matchConfidence: 0.42,
      matchReasons: ['LOW_CONFIDENCE'],
      candidates: [],
      errors: [
        { code: 'PLACE_NOT_FOUND', field: null, message: 'Không tìm thấy trên nhà cung cấp' },
      ],
      warnings: [],
    },
  ],
}

export const auditEntries = [
  {
    id: 'au-1',
    actor: 'huy.ng',
    action: 'cập nhật địa điểm',
    at: iso(120),
    before: { name: 'Chao Ban Cafe', avgVisitMinutes: 60 },
    after: { name: 'Chào Bạn Cafe & Space', avgVisitMinutes: 90 },
  },
  {
    id: 'au-2',
    actor: 'vy.vo',
    action: 'đổi trạng thái',
    at: iso(60 * 24 * 3),
    before: { status: 'review' },
    after: { status: 'published' },
  },
]
