import type {
  Collection,
  CmsPlaceDetail,
  DuplicatePair,
  FeatureFlag,
  ModerationQueue,
  OpsKpis,
  RankingConfig,
  Taxonomy,
} from '@/shared/api/contracts'
import type { ImportJob, ImportRow } from '@/shared/api/contracts-import'

/**
 * Dev/test fixtures. Vietnamese content on purpose — vi is the product
 * default and the layout has to survive real diacritics and real name length.
 * No real personal data: authors are pseudonymous handles.
 */

const now = Date.UTC(2026, 7, 27, 9, 0, 0)
const iso = (offsetMinutes: number) => new Date(now - offsetMinutes * 60_000).toISOString()

export const taxonomies: Taxonomy[] = [
  {
    id: 'tx-mood-quiet',
    kind: 'mood',
    key: 'quiet_peaceful',
    labels: { vi: 'Yên tĩnh', en: 'Quiet & peaceful' },
    sortOrder: 1,
    isActive: true,
    usageCount: 2814,
    synonyms: [
      { term: 'yên lặng', locale: 'vi' },
      { term: 'không ồn ào', locale: 'vi' },
      { term: 'peaceful', locale: 'en' },
    ],
  },
  {
    id: 'tx-mood-energetic',
    kind: 'mood',
    key: 'high_energy',
    labels: { vi: 'Sống động', en: 'Energetic' },
    sortOrder: 2,
    isActive: true,
    usageCount: 1402,
    synonyms: [{ term: 'nhộn nhịp', locale: 'vi' }],
  },
  {
    id: 'tx-mood-chill',
    kind: 'mood',
    key: 'chill_lounge',
    labels: { vi: 'Thư giãn', en: 'Relaxed lounge' },
    sortOrder: 3,
    isActive: false,
    usageCount: 0,
    synonyms: [],
  },
  {
    id: 'tx-cat-cafe',
    kind: 'category',
    key: 'cafe',
    labels: { vi: 'Cà phê', en: 'Cafe' },
    sortOrder: 1,
    isActive: true,
    usageCount: 6120,
    synonyms: [{ term: 'quán cà phê', locale: 'vi' }],
  },
  {
    id: 'tx-cat-street-food',
    kind: 'category',
    key: 'street_food',
    labels: { vi: 'Ăn vặt vỉa hè', en: 'Street food' },
    sortOrder: 2,
    isActive: true,
    usageCount: 3980,
    synonyms: [],
  },
  {
    id: 'tx-set-workfriendly',
    kind: 'setting',
    key: 'work_friendly',
    labels: { vi: 'Ngồi làm việc được', en: 'Work friendly' },
    sortOrder: 1,
    isActive: true,
    usageCount: 1180,
    synonyms: [{ term: 'có ổ cắm', locale: 'vi' }],
  },
  {
    id: 'tx-diet-vegan',
    kind: 'dietary',
    key: 'vegan',
    labels: { vi: 'Thuần chay', en: 'Vegan' },
    sortOrder: 1,
    isActive: true,
    usageCount: 214,
    synonyms: [],
  },
  {
    id: 'tx-acc-wheelchair',
    kind: 'accessibility',
    key: 'wheelchair_access',
    labels: { vi: 'Xe lăn tiếp cận được', en: 'Wheelchair access' },
    sortOrder: 1,
    isActive: true,
    usageCount: 96,
    synonyms: [],
  },
  {
    id: 'tx-spend-mid',
    kind: 'spending_style',
    key: 'mid_range',
    labels: { vi: 'Tầm trung', en: 'Mid range' },
    sortOrder: 2,
    isActive: true,
    usageCount: 4410,
    synonyms: [],
  },
  {
    id: 'tx-suit-couple',
    kind: 'suitability',
    key: 'couple_date',
    labels: { vi: 'Hẹn hò đôi', en: 'Couple date' },
    sortOrder: 1,
    isActive: true,
    usageCount: 5320,
    synonyms: [],
  },
]

export const places: CmsPlaceDetail[] = [
  {
    id: 'pl-chao-ban',
    name: 'Chào Bạn Cafe & Space',
    description: 'Cà phê nhiều cây, ba tầng, phù hợp ngồi làm việc cả buổi.',
    addressText: '126 Nguyễn Thị Minh Khai, Quận 3, TP.HCM',
    areaKey: 'hcm_q3',
    status: 'published',
    lat: 10.7769,
    lng: 106.6953,
    avgVisitMinutes: 90,
    isLodging: false,
    curatedRank: 3,
    taxonomyKeys: ['cafe', 'work_friendly', 'quiet_peaceful'],
    taxonomyIds: ['tx-cat-cafe', 'tx-set-workfriendly', 'tx-mood-quiet'],
    ratings: {
      googleRating: 4.8,
      googleRatingCount: 1240,
      gogoRating: 4.9,
      gogoRatingCount: 86,
      compositeScore: 0.91,
    },
    priceRange: { min: 45_000, max: 90_000, currency: 'VND' },
    freshnessVerifiedAt: iso(60 * 48),
    confidence: 0.92,
    sourceCount: 4,
    coverUrl: null,
    updatedAt: iso(120),
    updatedBy: 'huy.ng',
    // 0 = Sunday … 6 = Saturday, matching GoGo-BE's `vnDayMinute()`.
    hours: [
      { dayOfWeek: 0, openMinute: 480, closeMinute: 1350, isOvernight: false },
      { dayOfWeek: 1, openMinute: 420, closeMinute: 1350, isOvernight: false },
      { dayOfWeek: 2, openMinute: 420, closeMinute: 1350, isOvernight: false },
      { dayOfWeek: 3, openMinute: 420, closeMinute: 1350, isOvernight: false },
      { dayOfWeek: 4, openMinute: 420, closeMinute: 1350, isOvernight: false },
      { dayOfWeek: 5, openMinute: 420, closeMinute: 1380, isOvernight: false },
      { dayOfWeek: 6, openMinute: 480, closeMinute: 1380, isOvernight: false },
    ],
    prices: [
      {
        id: 'pr-1',
        priceMin: 45_000,
        priceMax: 90_000,
        currency: 'VND',
        unit: 'per_person',
        observedAt: iso(60 * 24 * 3),
        observedBy: 'vy.vo',
      },
    ],
    sources: [
      {
        kind: 'google_places',
        label: 'Google Places',
        fetchedAt: iso(60 * 48),
        attribution: 'Dữ liệu © Google',
      },
      {
        kind: 'editor',
        label: 'Biên tập viên xác minh',
        fetchedAt: iso(60 * 24 * 3),
        attribution: null,
      },
    ],
    media: [],
  },
  {
    id: 'pl-pho-bat-dan',
    name: 'Phở Bát Đàn',
    description: 'Phở bò truyền thống, xếp hàng tự bưng.',
    addressText: '49 Bát Đàn, Hoàn Kiếm, Hà Nội',
    areaKey: 'hn_hoankiem',
    status: 'published',
    lat: 21.0333,
    lng: 105.8452,
    avgVisitMinutes: 40,
    isLodging: false,
    curatedRank: null,
    taxonomyKeys: ['street_food'],
    taxonomyIds: ['tx-cat-street-food'],
    ratings: {
      googleRating: 4.5,
      googleRatingCount: 8210,
      gogoRating: 4.7,
      gogoRatingCount: 41,
      compositeScore: 0.88,
    },
    priceRange: { min: 50_000, max: 70_000, currency: 'VND' },
    freshnessVerifiedAt: iso(60 * 24 * 14),
    confidence: 0.78,
    sourceCount: 2,
    coverUrl: null,
    updatedAt: iso(60 * 26),
    updatedBy: 'vy.vo',
    hours: [],
    prices: [],
    sources: [
      {
        kind: 'google_places',
        label: 'Google Places',
        fetchedAt: iso(60 * 24 * 14),
        attribution: 'Dữ liệu © Google',
      },
    ],
    media: [],
  },
  {
    id: 'pl-tay-ho-sup',
    name: 'Tây Hồ Sunset SUP Club',
    description: null,
    addressText: '11 Tứ Hoa, Tây Hồ, Hà Nội',
    areaKey: 'hn_tayho',
    status: 'review',
    lat: 21.0705,
    lng: 105.8221,
    avgVisitMinutes: 120,
    isLodging: false,
    curatedRank: null,
    taxonomyKeys: ['high_energy'],
    taxonomyIds: ['tx-mood-energetic'],
    ratings: {
      googleRating: 4.2,
      googleRatingCount: 310,
      gogoRating: null,
      gogoRatingCount: 0,
      compositeScore: null,
    },
    priceRange: null,
    freshnessVerifiedAt: null,
    confidence: 0.44,
    sourceCount: 1,
    coverUrl: null,
    updatedAt: iso(60 * 72),
    updatedBy: 'dung.tr',
    hours: [],
    prices: [],
    sources: [],
    media: [],
  },
  {
    id: 'pl-goplay',
    name: 'GoPlay Entertainment',
    description: null,
    addressText: '812 Sư Vạn Hạnh, Quận 10, TP.HCM',
    areaKey: 'hcm_q10',
    status: 'suspended',
    lat: 10.7712,
    lng: 106.6702,
    avgVisitMinutes: 150,
    isLodging: false,
    curatedRank: null,
    taxonomyKeys: ['high_energy'],
    taxonomyIds: ['tx-mood-energetic'],
    ratings: {
      googleRating: 4.1,
      googleRatingCount: 520,
      gogoRating: 3.5,
      gogoRatingCount: 12,
      compositeScore: 0.61,
    },
    priceRange: { min: 120_000, max: 300_000, currency: 'VND' },
    freshnessVerifiedAt: iso(60 * 24 * 120),
    confidence: 0.35,
    sourceCount: 3,
    coverUrl: null,
    updatedAt: iso(60 * 24 * 12),
    updatedBy: 'system',
    hours: [],
    prices: [],
    sources: [],
    media: [],
  },
  {
    id: 'pl-com-tam-ba-ghien',
    name: 'Cơm Tấm Ba Ghiền',
    description: null,
    addressText: '84 Đặng Văn Ngữ, Phú Nhuận, TP.HCM',
    areaKey: 'hcm_phunhuan',
    status: 'draft',
    lat: 10.7955,
    lng: 106.6752,
    avgVisitMinutes: 45,
    isLodging: false,
    curatedRank: null,
    taxonomyKeys: ['street_food'],
    taxonomyIds: ['tx-cat-street-food'],
    ratings: {
      googleRating: 4.4,
      googleRatingCount: 4100,
      gogoRating: null,
      gogoRatingCount: 0,
      compositeScore: null,
    },
    priceRange: { min: 60_000, max: 120_000, currency: 'VND' },
    freshnessVerifiedAt: null,
    confidence: 0.5,
    sourceCount: 1,
    coverUrl: null,
    updatedAt: iso(60 * 5),
    updatedBy: 'import',
    hours: [],
    prices: [],
    sources: [],
    media: [],
  },
]

export const duplicatePairs: DuplicatePair[] = [
  {
    canonical: places[0]!,
    duplicate: {
      ...places[0]!,
      id: 'pl-chao-ban-bistro',
      name: 'Chào Bạn Bistro & Cafe',
      status: 'draft',
      sourceCount: 1,
    },
    similarity: 0.94,
    distanceMeters: 38,
    sharedProviderId: false,
    moves: { sources: 1, media: 3, prices: 1, reviews: 4, seeds: 2 },
  },
]

export const collections: Collection[] = [
  {
    id: 'col-cafe-q3',
    slug: 'top-cafe-song-ao-q3',
    locale: 'vi',
    title: 'Top cà phê sống ảo Quận 3',
    description: 'Danh sách biên tập cho hẹn hò cuối tuần.',
    status: 'published',
    startsAt: iso(60 * 24 * 10),
    endsAt: null,
    coverUrl: null,
    items: [
      {
        placeId: 'pl-chao-ban',
        name: 'Chào Bạn Cafe & Space',
        addressText: 'Quận 3',
        coverUrl: null,
        note: 'Ngồi làm việc',
      },
      {
        placeId: 'pl-com-tam-ba-ghien',
        name: 'Cơm Tấm Ba Ghiền',
        addressText: 'Phú Nhuận',
        coverUrl: null,
        note: null,
      },
    ],
    updatedAt: iso(60 * 20),
    updatedBy: 'vy.vo',
  },
  {
    id: 'col-hanoi-night',
    slug: 'an-dem-ha-noi',
    locale: 'vi',
    title: 'Ăn đêm Hà Nội',
    description: null,
    status: 'scheduled',
    startsAt: iso(-60 * 24),
    endsAt: iso(-60 * 24 * 30),
    coverUrl: null,
    items: [
      {
        placeId: 'pl-pho-bat-dan',
        name: 'Phở Bát Đàn',
        addressText: 'Hoàn Kiếm',
        coverUrl: null,
        note: null,
      },
    ],
    updatedAt: iso(60 * 50),
    updatedBy: 'huy.ng',
  },
]

export const moderationQueue: ModerationQueue = {
  reviews: [
    {
      kind: 'review',
      id: 'mr-1',
      createdAt: iso(34),
      severity: 'low',
      reason: null,
      placeId: 'pl-tay-ho-sup',
      placeName: 'Tây Hồ Sunset SUP Club',
      authorLabel: 'nguoi-dung-4821',
      rating: 5,
      body: 'Check-in view đẹp, hoàng hôn hồ Tây rất đáng đi.',
    },
  ],
  reports: [
    {
      kind: 'report',
      id: 'rp-1',
      createdAt: iso(12),
      severity: 'high',
      reason: null,
      placeId: 'pl-goplay',
      placeName: 'GoPlay Entertainment',
      authorLabel: 'nguoi-dung-1177',
      targetType: 'review',
      body: 'Đánh giá có ngôn từ xúc phạm nhân viên.',
    },
    {
      kind: 'report',
      id: 'rp-2',
      createdAt: iso(90),
      severity: 'medium',
      reason: null,
      placeId: 'pl-pho-bat-dan',
      placeName: 'Phở Bát Đàn',
      authorLabel: 'nguoi-dung-9004',
      targetType: 'place',
      body: 'Quán đã đóng cửa từ tháng trước.',
    },
  ],
  checkins: [
    {
      kind: 'checkin',
      id: 'ci-1',
      createdAt: iso(180),
      severity: 'low',
      reason: null,
      placeId: 'pl-chao-ban',
      placeName: 'Chào Bạn Cafe & Space',
      authorLabel: 'nguoi-dung-2210',
      photoCount: 3,
      body: 'Ảnh hoá đơn và không gian tầng 2.',
    },
  ],
  submissions: [
    {
      kind: 'submission',
      id: 'sb-1',
      createdAt: iso(60),
      severity: 'medium',
      reason: null,
      placeId: null,
      placeName: 'Lẩu Bò Ba Toa Sài Gòn',
      authorLabel: 'nguoi-dung-3390',
      body: 'Người dùng gửi địa điểm mới qua link Google Maps.',
      submissionCount: 3,
      googlePlaceId: 'ChIJ_submission_1',
      providerSnapshot: {
        name: 'Lẩu Bò Ba Toa Sài Gòn',
        address: '99 Cách Mạng Tháng 8, Quận 3, TP.HCM',
        rating: 4.3,
        ratingCount: 812,
        photoUrl: null,
        fetchedAt: iso(60),
        attributions: ['Dữ liệu © Google'],
      },
      matchedPlaceId: null,
    },
  ],
  stats: { pending: 5, resolvedToday: 228, avgResponseMinutes: 14 },
}

export const opsKpis: OpsKpis = {
  places: { total: 24_812, published: 21_240, draft: 1_402, suspended: 2_170 },
  freshnessScore: 0.942,
  freshnessDelta: 0.014,
  zeroResultRate: 0.0214,
  zeroResultDelta: -0.008,
  suggestionSuccessRate: 0.887,
  suggestionSuccessDelta: 0.021,
  budgetViolationRate: 0.031,
  providers: [
    {
      name: 'Google Places API',
      status: 'healthy',
      uptime: 0.9998,
      latencyMs: 142,
      errorRate: 0.0002,
      circuitBreaker: 'closed',
    },
    {
      name: 'Map tiles',
      status: 'healthy',
      uptime: 1,
      latencyMs: 34,
      errorRate: 0,
      circuitBreaker: 'closed',
    },
    {
      name: 'AI suggestion service',
      status: 'degraded',
      uptime: 0.984,
      latencyMs: 522,
      errorRate: 0.016,
      circuitBreaker: 'half_open',
    },
  ],
  series: Array.from({ length: 30 }, (_, index) => ({
    date: new Date(now - (29 - index) * 86_400_000).toISOString().slice(5, 10),
    zeroResultRate: 0.031 - index * 0.0003,
    suggestionSuccessRate: 0.82 + index * 0.0022,
  })),
  activity: [
    {
      id: 'ac-1',
      actor: 'huy.ng',
      action: 'cập nhật phân loại',
      resourceLabel: 'Phở Bát Đàn',
      resourceHref: '/places/pl-pho-bat-dan',
      at: iso(2),
    },
    {
      id: 'ac-2',
      actor: 'system',
      action: 'tạm ngưng theo nhà cung cấp',
      resourceLabel: 'GoPlay Entertainment',
      resourceHref: '/places/pl-goplay',
      at: iso(15),
    },
    {
      id: 'ac-3',
      actor: 'vy.vo',
      action: 'tạo bản nháp',
      resourceLabel: 'Tây Hồ Sunset SUP Club',
      resourceHref: '/places/pl-tay-ho-sup',
      at: iso(34),
    },
    {
      id: 'ac-4',
      actor: 'dung.tr',
      action: 'gộp bản trùng',
      resourceLabel: 'Chào Bạn Cafe & Space',
      resourceHref: '/places/pl-chao-ban',
      at: iso(60),
    },
  ],
  alerts: [
    {
      id: 'al-1',
      level: 'critical',
      title: 'Google Places API vượt ngưỡng chi phí',
      detail: 'Dự báo 420 USD/giờ',
    },
    {
      id: 'al-2',
      level: 'warning',
      title: 'AI refinement cạn lượt thử lại',
      detail: 'Đang chạy kết quả deterministic',
    },
  ],
}

export const rankingConfigs: RankingConfig[] = [
  {
    id: 'rc-2',
    key: 'suggestion.scoring',
    version: 2,
    status: 'active',
    weights: {
      preferenceMatch: 0.85,
      groupFairness: 0.6,
      distanceDecay: 0.75,
      budgetFit: 0.3,
      freshness: 0.4,
    },
    createdBy: 'minh.anh',
    createdAt: iso(120),
    approvedBy: 'vy.vo',
    approvedAt: iso(110),
    activatedAt: iso(105),
  },
  {
    id: 'rc-1',
    key: 'suggestion.scoring',
    version: 1,
    status: 'superseded',
    weights: {
      preferenceMatch: 0.8,
      groupFairness: 0.55,
      distanceDecay: 0.7,
      budgetFit: 0.35,
      freshness: 0.35,
    },
    createdBy: 'vy.vo',
    createdAt: iso(60 * 24 * 14),
    approvedBy: 'minh.anh',
    approvedAt: iso(60 * 24 * 14),
    activatedAt: iso(60 * 24 * 14),
  },
]

export const rankingBounds = [
  { weight: 'preferenceMatch', min: 0, max: 1, step: 0.01 },
  { weight: 'groupFairness', min: 0, max: 1, step: 0.01 },
  { weight: 'distanceDecay', min: 0, max: 1, step: 0.01 },
  { weight: 'budgetFit', min: 0, max: 1, step: 0.01 },
  { weight: 'freshness', min: 0, max: 1, step: 0.01 },
]

export const featureFlags: FeatureFlag[] = [
  {
    key: 'suggestion.ai_refinement',
    enabled: true,
    description:
      'Cho phép AI tinh chỉnh trên tập ứng viên đã hợp lệ. Tắt để quay về kết quả deterministic.',
    rolloutPercent: 100,
    isKillSwitch: true,
    updatedBy: 'minh.anh',
    updatedAt: iso(240),
  },
  {
    key: 'ingest.auto_publish_community',
    enabled: false,
    description: 'Tự động xuất bản địa điểm do người dùng gửi sau khi verify.',
    rolloutPercent: 0,
    isKillSwitch: false,
    updatedBy: 'vy.vo',
    updatedAt: iso(60 * 24 * 4),
  },
  {
    key: 'search.vi_synonym_expansion',
    enabled: true,
    description: 'Mở rộng truy vấn tiếng Việt bằng bảng từ đồng nghĩa.',
    rolloutPercent: 100,
    isKillSwitch: false,
    updatedBy: 'huy.ng',
    updatedAt: iso(60 * 24 * 9),
  },
]

export const importJobs: ImportJob[] = [
  {
    id: '4f0b8e10-0000-4000-8000-000000000209',
    status: 'review_required',
    mode: 'create_drafts',
    sourceType: 'xlsx',
    sourceFileName: 'hcm_q3_cafe_batch4.xlsx',
    totals: { rows: 500, processed: 234, success: 210, warnings: 18, failed: 6 },
    createdAt: iso(45),
    completedAt: null,
    createdBy: 'huy.ng',
    defaultCity: 'Hồ Chí Minh',
    rowsByStatus: { needs_confirmation: 12, duplicate: 4, ready: 210, failed: 6, pending: 266 },
    startedAt: iso(44),
    cancelledAt: null,
    reused: false,
    unmappedHeaders: ['ghi_chu_noi_bo'],
  },
  {
    id: '4f0b8e10-0000-4000-8000-000000000208',
    status: 'completed',
    mode: 'publish_approved',
    sourceType: 'csv',
    sourceFileName: 'chuoi_tra_sua_audit.csv',
    totals: { rows: 1240, processed: 1240, success: 1226, warnings: 9, failed: 14 },
    createdAt: iso(60 * 26),
    completedAt: iso(60 * 25),
    createdBy: 'vy.vo',
    defaultCity: null,
    rowsByStatus: { imported: 1226, failed: 14 },
    startedAt: iso(60 * 26),
    cancelledAt: null,
    reused: false,
    unmappedHeaders: [],
  },
  {
    id: '4f0b8e10-0000-4000-8000-000000000207',
    status: 'paused_provider_quota',
    mode: 'create_drafts',
    sourceType: 'google_sheet',
    sourceFileName: 'dalat_homestay_geocoded',
    totals: { rows: 300, processed: 22, success: 20, warnings: 2, failed: 0 },
    createdAt: iso(60 * 72),
    completedAt: null,
    createdBy: 'minh.anh',
    defaultCity: 'Đà Lạt',
    rowsByStatus: { pending: 278, ready: 20 },
    startedAt: iso(60 * 72),
    cancelledAt: null,
    reused: false,
    unmappedHeaders: [],
  },
]

export const importRows: Record<string, ImportRow[]> = {
  [importJobs[0]!.id]: [
    {
      id: 'row-12',
      rowNumber: 12,
      sourceRowId: '12',
      status: 'needs_confirmation',
      normalized: {
        name: 'Cộng Cà Phê',
        address: '120 Nguyễn Thị Minh Khai',
        city: 'Hồ Chí Minh',
        category: 'cafe',
      },
      resolvedGooglePlaceId: null,
      matchedPlaceId: null,
      matchedPlaceName: null,
      matchConfidence: 0.82,
      matchReasons: ['MULTIPLE_BRANCHES', 'EXACT_NAME_CITY'],
      candidates: [
        {
          googlePlaceId: 'ChIJ_cong_q3',
          name: 'Cộng Cà Phê – Nguyễn Thị Minh Khai',
          address: '120 Nguyễn Thị Minh Khai, Quận 3',
          confidence: 0.86,
          lat: 10.7771,
          lng: 106.6942,
          rating: 4.4,
          ratingCount: 1980,
          photoUrl: null,
          fetchedAt: iso(45),
          attributions: ['Dữ liệu © Google'],
        },
        {
          googlePlaceId: 'ChIJ_cong_q1',
          name: 'Cộng Cà Phê – Lý Tự Trọng',
          address: '26 Lý Tự Trọng, Quận 1',
          confidence: 0.71,
          lat: 10.7801,
          lng: 106.7002,
          rating: 4.3,
          ratingCount: 2410,
          photoUrl: null,
          fetchedAt: iso(45),
          attributions: ['Dữ liệu © Google'],
        },
      ],
      errors: [],
      warnings: [
        {
          code: 'DISTRICT_MISMATCH',
          field: 'district',
          message: 'Quận trong nguồn khác quận nhà cung cấp',
        },
      ],
    },
    {
      id: 'row-13',
      rowNumber: 13,
      sourceRowId: '13',
      status: 'ready',
      normalized: {
        name: 'The Coffee House Cao Thắng',
        address: '86 Cao Thắng',
        city: 'Hồ Chí Minh',
      },
      resolvedGooglePlaceId: 'ChIJ_tch_caothang',
      matchedPlaceId: null,
      matchedPlaceName: null,
      matchConfidence: 0.99,
      matchReasons: ['EXACT_PROVIDER_ID'],
      candidates: [],
      errors: [],
      warnings: [],
    },
    {
      id: 'row-14',
      rowNumber: 14,
      sourceRowId: '14',
      status: 'duplicate',
      normalized: {
        name: 'Chào Bạn Cafe',
        address: '126 Nguyễn Thị Minh Khai',
        city: 'Hồ Chí Minh',
      },
      resolvedGooglePlaceId: 'ChIJ_chao_ban',
      matchedPlaceId: 'pl-chao-ban',
      matchedPlaceName: 'Chào Bạn Cafe & Space',
      matchConfidence: 0.97,
      matchReasons: ['EXACT_PROVIDER_ID'],
      candidates: [],
      errors: [],
      warnings: [],
    },
    {
      id: 'row-15',
      rowNumber: 15,
      sourceRowId: '15',
      status: 'validation_failed',
      normalized: { name: 'Quán không tên', address: '' },
      resolvedGooglePlaceId: null,
      matchedPlaceId: null,
      matchedPlaceName: null,
      matchConfidence: null,
      matchReasons: [],
      candidates: [],
      errors: [{ code: 'ADDRESS_REQUIRED', field: 'address', message: 'Thiếu địa chỉ' }],
      warnings: [],
    },
    {
      id: 'row-16',
      rowNumber: 16,
      sourceRowId: '16',
      status: 'unresolved',
      normalized: { name: 'Cafe Tầng Thượng 3B', address: 'Ngõ 12 Trần Quốc Toản' },
      resolvedGooglePlaceId: null,
      matchedPlaceId: null,
      matchedPlaceName: null,
      matchConfidence: 0.42,
      matchReasons: ['LOW_CONFIDENCE'],
      candidates: [],
      errors: [
        { code: 'PLACE_NOT_FOUND', field: null, message: 'Không tìm thấy trên nhà cung cấp' },
      ],
      warnings: [],
    },
  ],
}

export const auditEntries = [
  {
    id: 'au-1',
    actor: 'huy.ng',
    action: 'cập nhật địa điểm',
    at: iso(120),
    before: { name: 'Chao Ban Cafe', avgVisitMinutes: 60 },
    after: { name: 'Chào Bạn Cafe & Space', avgVisitMinutes: 90 },
  },
  {
    id: 'au-2',
    actor: 'vy.vo',
    action: 'đổi trạng thái',
    at: iso(60 * 24 * 3),
    before: { status: 'review' },
    after: { status: 'published' },
  },
]
