export const styles = {
  body: 'flex flex-col gap-4',
  section: 'flex flex-col gap-2',
  sectionTitle: 'text-[13px] font-bold uppercase tracking-wide text-text-muted',
  facts: 'flex flex-col gap-2 text-[13px]',
  factRow: 'flex items-start justify-between gap-3',
  factLabel: 'shrink-0 text-text-muted',
  factValue: 'min-w-0 text-right font-semibold text-text break-words',
  mono: 'font-mono text-[12px] text-text',
  link: 'text-coral underline underline-offset-2',
  note: 'rounded-compact border border-line bg-surface-sunken px-3 py-2 text-[13px] text-text',
  hint: 'flex items-start gap-2 rounded-compact border border-line bg-surface-sunken px-3 py-2 text-xs text-text-muted',
  warn: 'flex items-start gap-2 rounded-compact border border-amber/45 bg-amber-soft px-3 py-2 text-xs text-text',
  grid: 'grid gap-3 sm:grid-cols-2',
  tagRow: 'flex flex-wrap gap-2',
  tag: 'inline-flex items-center gap-1 rounded-full border border-line bg-surface-sunken px-2 py-1 text-[12px] text-text',
  tagRemove: 'rounded-full p-0.5 text-text-muted hover:bg-line hover:text-text',
  results: 'flex flex-col gap-1',
  result:
    'flex w-full flex-col rounded-compact border border-line px-3 py-2 text-left text-[13px] hover:border-line-strong hover:bg-surface-sunken',
  resultName: 'font-semibold text-text',
  resultMeta: 'text-[12px] text-text-muted',
  historyRow: 'flex flex-col gap-0.5 border-l-2 border-line pl-3 text-[12px]',
  historyAction: 'font-semibold text-text',
  historyMeta: 'text-text-muted',
  footer: 'flex flex-wrap items-center justify-end gap-2',
} as const
