export const styles = {
  layout: 'grid gap-5 xl:grid-cols-3',
  list: 'flex flex-col gap-3 xl:col-span-2',
  row: 'flex w-full flex-col gap-2 rounded-card border border-line bg-surface p-4 text-left',
  rowActive: 'border-coral bg-coral-soft/40',
  rowIdle: 'hover:border-line-strong hover:bg-surface-sunken',
  rowTop: 'flex flex-wrap items-center justify-between gap-2',
  placeId: 'font-mono text-[12px] text-text-muted',
  meta: 'flex flex-wrap items-center gap-3 text-[12px] text-text-muted',
  count: 'font-semibold tabular-nums text-text',
  note: 'text-[13px] text-text',
  detail: 'h-fit rounded-card border border-line bg-surface p-4',
  detailTitle: 'text-[15px] font-bold text-text',
  facts: 'mt-3 flex flex-col gap-2 text-[13px]',
  factRow: 'flex items-start justify-between gap-3',
  factLabel: 'text-text-muted',
  factValue: 'text-right font-semibold text-text',
  actions: 'mt-4 flex flex-col gap-2',
  actionRow: 'flex flex-wrap gap-2',
  hint: 'flex items-start gap-2 rounded-compact border border-amber/45 bg-amber-soft px-3 py-2 text-xs text-text',
  more: 'mt-2 self-center',
} as const
