export const styles = {
  toolbar: 'flex flex-wrap items-center justify-between gap-3',
  windowGroup: 'inline-flex rounded-pill border border-line bg-surface p-0.5',
  windowButton:
    'min-h-11 rounded-pill px-3 py-1 text-xs font-semibold text-text-muted transition-colors hover:text-text focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-coral',
  windowButtonActive: 'bg-coral-soft text-coral-deep',
  meta: 'flex flex-wrap items-center gap-x-3 gap-y-1 text-[11px] text-text-subtle',
  banner: 'flex items-start gap-3 rounded-card border px-4 py-3 text-[13px] leading-relaxed',
  bannerWarn: 'border-amber/40 bg-amber-soft text-amber',
  bannerInfo: 'border-line bg-surface-muted text-text-muted',
  cardGrid: 'grid gap-4 sm:grid-cols-2 xl:grid-cols-3',
  cardSub: 'text-[11px] leading-relaxed text-text-subtle',
  unknownList: 'mt-1 flex flex-wrap gap-1',
  idChip:
    'rounded-pill border border-line-strong bg-surface-sunken px-2 py-0.5 font-mono text-[10px] text-text-muted',
  providerHead: 'flex flex-wrap items-center gap-2',
  providerName: 'font-display text-[15px] font-bold text-text',
  providerFacts: 'flex flex-wrap items-center gap-x-3 gap-y-1 text-[11px] text-text-subtle',
  scroller: 'overflow-x-auto',
  table: 'w-full border-collapse text-[13px]',
  th: 'border-b border-line px-3 py-2 text-left text-[11px] font-semibold tracking-wide text-text-subtle uppercase',
  thNum:
    'border-b border-line px-3 py-2 text-right text-[11px] font-semibold tracking-wide text-text-subtle uppercase',
  td: 'border-b border-line/70 px-3 py-2 align-top',
  tdNum: 'border-b border-line/70 px-3 py-2 text-right align-top tabular-nums',
  rowButton:
    'w-full text-left focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-coral',
  serviceName: 'font-semibold text-text',
  serviceId: 'font-mono text-[11px] text-text-subtle',
  money: 'font-semibold text-text tabular-nums',
  muted: 'text-[11px] text-text-subtle',
  unknownCell: 'text-[11px] text-text-subtle italic',
  meterLine: 'font-mono text-[11px] text-text-muted tabular-nums',
  sectionList: 'flex flex-col gap-5',
  drawerBlock: 'flex flex-col gap-4',
  drawerLabel: 'text-[11px] font-semibold tracking-wide text-text-subtle uppercase',
  drawerRow: 'flex items-baseline justify-between gap-4 border-b border-line/70 py-1.5 text-[13px]',
  sourceRow: 'rounded-compact border border-line bg-surface-muted px-3 py-2',
  sourceHead: 'flex flex-wrap items-center gap-2',
  sourceId: 'font-mono text-[12px] text-text',
  operation: 'rounded-compact border border-line bg-surface px-3 py-2',
  operationHead: 'flex flex-wrap items-center gap-2',
  runLink: 'font-semibold text-coral-deep underline-offset-2 hover:underline',
  totals: 'grid gap-4 sm:grid-cols-3',
  note: 'flex items-start gap-2 rounded-compact border border-line bg-surface-muted px-3 py-2 text-xs text-text-muted',
  noteWarn:
    'flex items-start gap-2 rounded-compact border border-amber/40 bg-amber-soft px-3 py-2 text-xs text-text',
} as const
