export const styles = {
  kpiGrid: 'grid gap-4 sm:grid-cols-2 xl:grid-cols-4',
  splitGrid: 'grid gap-4 xl:grid-cols-3',
  wide: 'xl:col-span-2',
  chartFrame: 'relative h-44 w-full',
  chartLegend: 'mt-2 flex flex-wrap items-center gap-4 text-[11px] text-text-muted',
  legendSwatch: 'inline-block h-2 w-4 rounded-pill align-middle',
  axis: 'mt-1 flex justify-between text-[11px] text-text-subtle',
  providerRow: 'border-b border-line pb-3 last:border-b-0 last:pb-0',
  providerHead: 'mb-1.5 flex items-center justify-between gap-2',
  providerName: 'text-[13px] font-semibold text-text',
  providerStats: 'grid grid-cols-3 gap-2 text-[11px]',
  statLabel: 'text-text-subtle',
  statValue: 'font-semibold tabular-nums text-text',
  statValueBad: 'font-semibold tabular-nums text-danger',
  activityRow:
    'flex items-baseline justify-between gap-3 border-b border-line py-2 last:border-b-0',
  activityText: 'min-w-0 text-[13px]',
  activityActor: 'font-semibold text-text',
  activityAction: 'text-text-muted',
  activityTarget: 'font-semibold text-coral-deep hover:underline',
  activityTime: 'shrink-0 text-[11px] tabular-nums text-text-subtle',
  alertCritical: 'rounded-compact border border-danger/40 bg-danger-soft p-3',
  alertWarning: 'rounded-compact border border-amber/45 bg-amber-soft p-3',
  alertLabel: 'text-[10px] font-bold uppercase tracking-wide',
  alertTitle: 'mt-1 text-[13px] font-semibold text-text',
  alertDetail: 'text-xs text-text-muted',
  stack: 'flex flex-col gap-3',
} as const
