export const styles = {
  layout: 'grid gap-5 xl:grid-cols-3',
  main: 'flex flex-col gap-5 xl:col-span-2',
  side: 'flex flex-col gap-5',
  weightRow: 'mb-4 last:mb-0',
  weightHead: 'mb-1.5 flex items-center justify-between gap-2',
  weightLabel: 'text-[13px] font-semibold text-text',
  weightValue: 'text-[13px] font-bold tabular-nums text-coral-deep',
  slider: 'h-1.5 w-full cursor-pointer appearance-none rounded-pill',
  bounds: 'mt-0.5 flex justify-between text-[10px] tabular-nums text-text-subtle',
  flagRow:
    'flex flex-wrap items-start justify-between gap-3 border-b border-line py-3 last:border-b-0',
  flagKey: 'font-mono text-[13px] font-semibold text-text',
  flagDesc: 'mt-0.5 max-w-lg text-xs text-text-muted',
  flagMeta: 'mt-1 text-[11px] text-text-subtle',
  version: 'rounded-compact border p-3',
  versionActive: 'border-coral/40 bg-coral-soft/40',
  versionIdle: 'border-line',
  versionHead: 'mb-1 flex items-center justify-between gap-2',
  versionLabel: 'text-[13px] font-semibold text-text',
  versionMeta: 'text-[11px] text-text-subtle',
  providerCard: 'rounded-compact border border-line p-3',
  providerHead: 'mb-2 flex items-center justify-between gap-2',
  providerGrid: 'grid grid-cols-3 gap-2 text-[11px]',
  fourEyes:
    'flex items-start gap-2 rounded-compact border border-amber/45 bg-amber-soft px-3 py-2 text-xs text-text',
  flagPayload:
    'mt-1 max-h-24 overflow-auto rounded-compact bg-surface-sunken p-2 font-mono text-[11px] text-text-muted',
  experimentRow: 'border-b border-line py-4 last:border-b-0',
  experimentHead: 'flex flex-wrap items-start justify-between gap-3',
  experimentKey: 'font-mono text-[13px] font-semibold text-text',
  experimentDesc: 'mt-0.5 max-w-lg text-xs text-text-muted',
  splitBar: 'mt-3 flex h-3 w-full overflow-hidden rounded-pill bg-surface-sunken',
  splitSegment: 'h-full',
  splitLegend: 'mt-2 flex flex-wrap gap-x-4 gap-y-1 text-[11px] text-text-muted',
  splitDot: 'mr-1 inline-block h-2 w-2 rounded-full align-middle',
  variantRow: 'grid grid-cols-[1fr_6rem_auto] items-end gap-2',
  metricGrid: 'grid gap-3 sm:grid-cols-2 xl:grid-cols-4',
  metricCard: 'rounded-compact border border-line bg-surface-muted px-3 py-2',
  metricLabel: 'block text-[11px] text-text-subtle',
  metricValue: 'block font-display text-xl font-extrabold tabular-nums text-text',
  metricHint: 'mt-1 block text-[11px] text-text-subtle',
  skippedList: 'mt-2 max-h-32 overflow-auto text-[11px] text-text-subtle',
} as const
